// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ27QeqRNfDhF_LQioK0AjxhAwCGlaU-M',
    appId: '1:963863199423:web:8a5f95110a5bf9f53f900a',
    messagingSenderId: '963863199423',
    projectId: 'youbuddy-96438',
    authDomain: 'youbuddy-96438.firebaseapp.com',
    databaseURL: 'https://youbuddy-96438-default-rtdb.firebaseio.com',
    storageBucket: 'youbuddy-96438.appspot.com',
    measurementId: 'G-0TFMJE65T9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4WE_FR-9PdIt1e7ikQutn8h1bCg16Osc',
    appId: '1:963863199423:android:83d92e5d616e0b7f3f900a',
    messagingSenderId: '963863199423',
    projectId: 'youbuddy-96438',
    databaseURL: 'https://youbuddy-96438-default-rtdb.firebaseio.com',
    storageBucket: 'youbuddy-96438.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3nSqAG2LNntFIUgecfeLATTS9vnQdXvc',
    appId: '1:963863199423:ios:ccc8038b7f6f91053f900a',
    messagingSenderId: '963863199423',
    projectId: 'youbuddy-96438',
    databaseURL: 'https://youbuddy-96438-default-rtdb.firebaseio.com',
    storageBucket: 'youbuddy-96438.appspot.com',
    iosClientId: '963863199423-73srcc07f47qlijdefe8u0328rshhif1.apps.googleusercontent.com',
    iosBundleId: 'com.example.youbuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3nSqAG2LNntFIUgecfeLATTS9vnQdXvc',
    appId: '1:963863199423:ios:94a3478d034253843f900a',
    messagingSenderId: '963863199423',
    projectId: 'youbuddy-96438',
    databaseURL: 'https://youbuddy-96438-default-rtdb.firebaseio.com',
    storageBucket: 'youbuddy-96438.appspot.com',
    iosClientId: '963863199423-4vde60veeks61mqa84sk77dl4ovjdat2.apps.googleusercontent.com',
    iosBundleId: 'com.example.youbuddy.RunnerTests',
  );
}
