name: youbuddy
description: >-
  YouBuddy You Buddy.
version: 0.1.0

environment:
  sdk: '>=2.12.0 <3.9.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.20.0
  cloud_firestore: ^4.12.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1
  charts_flutter: ^0.12.0
  firebase_auth: ^4.12.1
  csv: ^5.1.1
  file_saver: ^0.2.11

flutter:
  uses-material-design: true