name: youbuddy
description: >-
  YouBuddy You Buddy.
version: 0.1.0

environment:
  sdk: '>=2.12.0 <3.9.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.0.0
  cloud_firestore: ^5.0.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1
  charts_flutter: ^0.12.0
  firebase_auth: ^5.0.0
  csv: ^6.0.0
  file_saver: ^0.2.11
  oauth2: ^2.0.2
  cloud_functions: ^5.0.0


flutter:
  uses-material-design: true